version: '3'
services:
    opcplc:
        image: mcr.microsoft.com/iotedge/opc-plc:latest
        container_name: opcplc
        hostname: opcplc
        ports:
            - "50000:50000"
        command: --aa
    publisher:
        image: mcr.microsoft.com/iotedge/opc-publisher:2.4.1
        container_name: publisher
        depends_on:
            - opcplc
        hostname: publisher
        volumes:
            - '${_REPO_ROOT}:/appdata'
        ports:
            - "62222:62222"
        command: publisher --aa --pf /appdata/publishednodes.json --iotcentral=True --fetchdisplayname=True --iothubmessagesize=0 --iothubsendinterval=0 --diagnosticsinterval=10 --deviceconnectionstring=${_DEVICE_CS}
